### ISSUE TITLE
Publish 0.2.0 (and 0.2.1?) on NPM

### ISSUE THREAD

**Issue by okybr** [foss-haas/rfc2253#15]
Hello,

this package seems quite useful; thank you for the work!

But the latest version, [0.2.0](https://github.com/foss-haas/rfc2253/releases/tag/v0.2.0), has [not been published on NPM](https://www.npmjs.com/package/rfc2253?activeTab=versions).

Also, since version 0.2.0, there have been [some changes](https://github.com/foss-haas/rfc2253/commits/master) made but they haven't been released yet.

That's why I'd like to suggest to release version 0.2.1 and publish it on NPM so that everybody can use it easily.

**Comment by okybr** [comment]
@pluma ;)

**Comment by pluma** [comment]
The changes since the tag only affect dev dependencies, so they're not worth a bugfix release. I've just published 0.2.0 on npm though, thanks for spotting this.

**Comment by pluma** [comment]
BTW if you find this package useful, please consider creating a PR for expanding the API description. I haven't touched the code in years and it works good enough for me right now so I don't have the time or motivation to expand on those "TODOs" right now :)

There also seems to be a bug with multivalue RDNs that I'm not sure how to even begin to address (see #14).
